#!/usr/bin/env bash
# build-ff-import.sh — build an OrcaSlicer-importable package of FlashForge's
# CURRENT profiles (from the latest Flash Studio) wherever they are newer than,
# or missing from, upstream OrcaSlicer's bundled Flashforge vendor.
#
# For each category (filament / process / machine):
#   - flatten every Flash Studio preset's `inherits` chain (self-contained)
#   - compare the raw Flash Studio preset to upstream OrcaSlicer's same-named one
#   - KEEP it if upstream lacks it (missing) or its content differs (newer)
#   - SKIP it only if byte-identical to upstream (no point shipping a dup)
# Output: import-into-orca/<category>/ + DELTA-REPORT.md.
#
# Needs: curl, unzip, python3, gh. Re-run to refresh; bump FS_URL for new releases.
set -euo pipefail
cd "$(dirname "$0")"

FS_URL="https://flashforge-resource.oss-us-east-1.aliyuncs.com/Flash%20Studio/Flash_Studio_ubuntu24.04_V1.7.8-.zip"
FS_VER="1.7.8"
OUT="import-into-orca"
W="$(mktemp -d)"; trap 'rm -rf "$W"' EXIT

echo "[1/4] download + extract Flash Studio ${FS_VER} ..."
curl -fsSL -o "$W/fs.zip" "$FS_URL"
unzip -q "$W/fs.zip" -d "$W"
chmod +x "$W"/*.AppImage
( cd "$W" && ./*.AppImage --appimage-extract >/dev/null 2>&1 )
P="$W/squashfs-root/resources/profiles"
[ -d "$P/Flashforge" ] || { echo "no Flashforge profiles in AppImage"; exit 1; }

echo "[2/4] flatten every preset (resolve inherits) ..."
for cat in filament process machine; do
    python3 flatten.py "$P" "$cat" "$W/flat/$cat" >/dev/null
done

echo "[3/4] fetch upstream OrcaSlicer Flashforge vendor + select missing/newer ..."
rm -rf "$OUT"; mkdir -p "$OUT"
declare -A TOT MISS NEW SAME
for cat in filament process machine; do
    mkdir -p "$OUT/$cat" "$W/up/$cat"
    gh api "repos/SoftFever/OrcaSlicer/contents/resources/profiles/Flashforge/$cat" \
        --jq '.[] | .name + "\t" + .download_url' 2>/dev/null > "$W/up-$cat.list" || true
    # download upstream raw for the names we have
    while IFS=$'\t' read -r nm url; do [ -n "${url:-}" ] && curl -fsSL "$url" -o "$W/up/$cat/$nm" 2>/dev/null || true; done < "$W/up-$cat.list"
    tot=0; miss=0; new=0; same=0
    for f in "$P/Flashforge/$cat"/*.json; do
        b="$(basename "$f")"; tot=$((tot+1))
        if [ ! -f "$W/up/$cat/$b" ]; then
            cp "$W/flat/$cat/$b" "$OUT/$cat/"; miss=$((miss+1))
        elif ! python3 -c "import json,sys;sys.exit(0 if json.load(open(sys.argv[1]))==json.load(open(sys.argv[2])) else 1)" "$f" "$W/up/$cat/$b" 2>/dev/null; then
            cp "$W/flat/$cat/$b" "$OUT/$cat/"; new=$((new+1))
        else
            same=$((same+1))
        fi
    done
    TOT[$cat]=$tot; MISS[$cat]=$miss; NEW[$cat]=$new; SAME[$cat]=$same
    echo "    $cat: $((miss+new)) shipped ($miss missing + $new newer), $same identical-skipped of $tot"
done

echo "[4/4] build-plate assets + delta report ..."
mkdir -p "$OUT/buildplates"
for a in $(grep -rhoE '[^"/]+\.(png|stl|STL)' "$OUT/machine" 2>/dev/null | sort -u); do
    s="$(find "$P/Flashforge" -name "$a" 2>/dev/null | head -1)"; [ -n "$s" ] && cp "$s" "$OUT/buildplates/" 2>/dev/null || true
done
[ -z "$(ls -A "$OUT/buildplates" 2>/dev/null)" ] && rmdir "$OUT/buildplates"

{
  echo "# Delta report — Flash Studio ${FS_VER} vs upstream OrcaSlicer"
  echo
  echo "What this package ships: FlashForge presets that upstream OrcaSlicer either"
  echo "lacks (missing) or carries an older copy of (newer). Byte-identical presets"
  echo "are skipped. Generated by build-ff-import.sh."
  echo
  echo "| category | shipped | missing upstream | newer than upstream | identical (skipped) | FF total |"
  echo "|---|---:|---:|---:|---:|---:|"
  for cat in machine filament process; do
    echo "| $cat | $(( ${MISS[$cat]} + ${NEW[$cat]} )) | ${MISS[$cat]} | ${NEW[$cat]} | ${SAME[$cat]} | ${TOT[$cat]} |"
  done
} > "$OUT/DELTA-REPORT.md"

echo "done: $(find "$OUT" -name '*.json' | wc -l) presets in $OUT/ (see DELTA-REPORT.md)"
